### ISSUE TITLE
Dupla-Sena: Numeros mais/menos sorteados

### ISSUE THREAD

**Issue by andrenakazato** [willowmagrini/ts_loterias#1]
![001](https://cloud.githubusercontent.com/assets/5948306/11446995/7df693c8-9526-11e5-925c-f148fc8eb8f7.png)
> API: Precisa Puxar 15 numeros

**Comment by andrenakazato** [comment]
.maiores-premios .circulo-m (
padding: 1px;
)
Eu farei arrumação de CSS

**Comment by matheusgimenez** [comment]
Opa @andrenakazato, isso dos numeros mais sorteados estarem aparecendo circulos a mais eu já tinha resolvido.. ta rolando denovo?

**Comment by andrenakazato** [comment]
@matheusgimenez Circuloas a mais nao aparecem mais, sem problemas.

Decido ficar somente com os numeros vindos da API.
