### ISSUE TITLE
Novo Menu

### ISSUE THREAD

**Issue by carlosmartel** [willowmagrini/ts_loterias#2]
Fazer o menu baseado no meu layout. Segue a referência (atenção: isso é só a referência. Eu vou mandar o layout final) 

![702222921_50991_14225394698604103170](https://cloud.githubusercontent.com/assets/5678578/11447053/217a8f0e-9527-11e5-927b-fd36c8b8e45f.jpg)

**Comment by andrenakazato** [comment]
O aintigo poderia te4r sido arrumado somente com .menu-item-has-children .dropdown-menu {
    width: inherit;
}
![004](https://cloud.githubusercontent.com/assets/5948306/11447191/49055fac-9529-11e5-9b91-3d20e14b4db7.png)
Vai ser trocado por completo então?

**Comment by carlosmartel** [comment]
@andrenakazato @willowmagrini Vai ser trocado por este: (tb está na pasta do drive)
Não tem mais pipe | e nem seta ▼
![screen shot 2015-11-28 at 10 05 37 pm](https://cloud.githubusercontent.com/assets/5678578/11454641/fabd8fb6-961a-11e5-8cf2-5b9fd4420977.png)


[tslot_menu_final.pdf](https://github.com/willowmagrini/ts_loterias/files/46438/tslot_menu_final.pdf)

**Comment by willowmagrini** [comment]
@carlosmartel preparei a lógica mas não fiz o css pra deixar igual ao seu, eu acho que já tem uma usabilidade boa e para resolver o problema dos itens pai (exemplo se o cara quer entyrar na mega-sena geral) podemos colocar um item no sub-menu chamado a mega-sena.

**Comment by willowmagrini** [comment]
Adicionei no menu loterias nacionais um "todas" que remete à página com todas as loterias nacionais

**Comment by carlosmartel** [comment]
Essa página de "todas" as Loterias é meio inútil, não acha?
E sobre o menu, eu não entendi..

**Comment by carlosmartel** [comment]
Ah acho que entendi! Você está certo. Falta um "todas" depois de loterias nacionais e falta um "a mega-sena" ou "página principal", depois que ele entrar no sub-menu branco.

**Comment by carlosmartel** [comment]
E pelo que eu entendi o css não tá pronto, é isso?
