### ISSUE TITLE
Arrumar exibição de numeros dos Maiores Premios com Time do Coracao

### ISSUE THREAD

**Issue by andrenakazato** [willowmagrini/ts_loterias#25]
![image](https://cloud.githubusercontent.com/assets/5948306/11448097/d9e19a54-9538-11e5-96dd-5dff59aeb9ba.png)

> Front/Design: Precisa arrumar o design para inserir API
Inserir o icone de coração
Afetará:
	http://eaxdesign.com.br/sorteonline/resultados/
	http://eaxdesign.com.br/sorteonline/resultados/timemania/

**Comment by carlosmartel** [comment]
@andrenakazato @matheusgimenez  
é só colocar o número correto de números sorteados nesse dia + o time do coração
Tenho que mandar o coração em svg ou melhor fazer um coração css? https://css-tricks.com/examples/ShapesOfCSS/

**Comment by andrenakazato** [comment]
@matheusgimenez Arrumar lógica de exibição de resultados de premios do timemania
