### ISSUE TITLE
Quantidade de Numeros exibidos em mais/menos sorteados nas paginas individuais

### ISSUE THREAD

**Issue by andrenakazato** [willowmagrini/ts_loterias#26]
![image](https://cloud.githubusercontent.com/assets/5948306/11448103/fc2d810e-9538-11e5-8ad6-2363be42e865.png)

![image](https://cloud.githubusercontent.com/assets/5948306/11448117/277ecab6-9539-11e5-9e8f-acf4656b7bf2.png)

> Design/API: Dupla-Sena sortea-se 6 números duas vezes. Como será exibido aqui?
> Design/API: Quina se sorteia 5 números apenas e puxaram 7. Discutir

**Comment by carlosmartel** [comment]
Tem que ver com o @matheusgimenez como está vindo na API. Mas o correto pra mim seria duas vezes 6 bolinhas na Loteca e só 5 na quina.

**Comment by carlosmartel** [comment]
São dois sorteios na estatísticas de mais e menos sorteados

![screen shot 2015-11-30 at 12 10 31 am](https://cloud.githubusercontent.com/assets/5678578/11462058/aceb87e4-96f5-11e5-83fa-c8bc5bba21c5.png)


![screen shot 2015-11-30 at 12 10 43 am](https://cloud.githubusercontent.com/assets/5678578/11462059/b376de88-96f5-11e5-9c7a-b168fd18095b.png)

**Comment by matheusgimenez** [comment]
Me expliquem por favor isso da dupla-sena melhor.. @carlosmartel @andrenakazato 

Vocês querem que mostre dois grupos de "bolinhas"?

**Comment by andrenakazato** [comment]
@matheusgimenez Aqui era para exibir 2 conjuntos de 6 bolinhas para **Dupla** e somente 5 bolinhas paar **Quina**, mas creioq ue se veio assim da APi, não tem jeito. E eles não reclamaram. Fecharei a issue.
