### ISSUE TITLE
Dupla-Sena: Remover Label Repetida

### ISSUE THREAD

**Issue by andrenakazato** [willowmagrini/ts_loterias#27]
![image](https://cloud.githubusercontent.com/assets/5948306/11448111/131d9426-9539-11e5-858c-87bb88ba2c3c.png)

> Design: Creio que repetir isso seja desnecessário. Discutir.
Isso se aplicaria nas páginas: http://eaxdesign.com.br/sorteonline/resultados/ e http://eaxdesign.com.br/sorteonline/resultados/dupla-sena/

**Comment by carlosmartel** [comment]
Pode tirar
