### ISSUE TITLE
Maiores Premios: inserir API

### ISSUE THREAD

**Issue by andrenakazato** [willowmagrini/ts_loterias#29]
http://eaxdesign.com.br/sorteonline/loterias-nacionais/loteca/estatisticas/maiores-premios/
http://eaxdesign.com.br/sorteonline/loterias-nacionais/lotogol/estatisticas/maiores-premios/

> Design: Possui dezenas.

**Comment by carlosmartel** [comment]
Retirar as dezenas. 
Colocar o triângulo nas tabs

**Comment by matheusgimenez** [comment]
feito no ultimo commit
