### ISSUE TITLE
Texto - Página de Resultados

### ISSUE THREAD

**Issue by carlosmartel** [willowmagrini/ts_loterias#32]
Deixar o primeiro parágrafo de todos os resultados em duas linhas com Loren Ipsun (igual layout). Depois jogar todo o texto (ver imagem) da página para depois do box de resultado. 

![screen shot 2015-11-28 at 6 57 04 pm](https://cloud.githubusercontent.com/assets/5678578/11453808/d735afb6-9600-11e5-9029-b7f3be16b3a5.png)

**Comment by willowmagrini** [comment]
@carlosmartel Não compreendi, a imagem está igual ao site atual.

**Comment by carlosmartel** [comment]
Comenta lah dentro do issue
Em 28/11/2015 23:30, "willowmagrini" <notifications@github.com> escreveu:

**Comment by carlosmartel** [comment]
Isso é um print do site. É pra ver o Layout, colocar duas linhas de Loren Ipsum antes do box de resultado e todo o resto de texto depois da pessoa ter visto o resultado.
