### ISSUE TITLE
Ajustar cores e fontes

### ISSUE THREAD

**Issue by carlosmartel** [willowmagrini/ts_loterias#34]
acertar as fontes de todas loterias e a cor da logotol (Comparar com o layout - ver mais abaixo)

aqui a fonte é condensed. nao está

![screen shot 2015-11-28 at 7 15 13 pm](https://cloud.githubusercontent.com/assets/5678578/11453877/3585fe20-9603-11e5-8a26-4a12e4889428.png)

![screen shot 2015-11-28 at 7 07 37 pm](https://cloud.githubusercontent.com/assets/5678578/11453838/24a314e0-9602-11e5-8c4c-0f1b3ef2263d.png)

Comparar com o layout 
![screen shot 2015-11-28 at 7 08 39 pm](https://cloud.githubusercontent.com/assets/5678578/11453842/52e3b8aa-9602-11e5-903c-b450adb02ea5.png)

**Comment by willowmagrini** [comment]
@andrenakazato coloquei vc nessa porque já fez a revisão das fontes nas páginas de loterias, ok?

**Comment by andrenakazato** [comment]
@carlosmartel @willowmagrini Issue já localizada em https://github.com/willowmagrini/ts_loterias/issues/24
