### ISSUE TITLE
Input de resultados

### ISSUE THREAD

**Issue by carlosmartel** [willowmagrini/ts_loterias#35]
Fazer igual ao do box de cadastro. O design tá certo mas falta inserir o placeholder correto.

![screen shot 2015-11-28 at 7 20 39 pm](https://cloud.githubusercontent.com/assets/5678578/11453913/12913f96-9604-11e5-9f21-9b5f7c081fbf.png)
![screen shot 2015-11-28 at 7 21 31 pm](https://cloud.githubusercontent.com/assets/5678578/11453914/143e7368-9604-11e5-96ac-3f20b7a7d7b6.png)

**Comment by willowmagrini** [comment]
https://github.com/willowmagrini/ts_loterias/commit/8b0d2ccd67e58a46f2b42ef4fae54671ca251000

**Comment by carlosmartel** [comment]
@willowmagrini @andrenakazato O cliente é chato com alinhamento :( 
Veja tb que é caixa alta a frase sorteio anterior e o texto "pesquisa por número do concurso" não é essa fonte.
O botão é do lado. A seta não é fonte < (tem que pegar a do layout e fazer png ou fontawesome)

![screen shot 2015-11-29 at 4 02 25 pm](https://cloud.githubusercontent.com/assets/5678578/11458919/6d579bd4-96b1-11e5-8233-f0e6dbf414b9.png)
