### ISSUE TITLE
Resultado Mega-sena

### ISSUE THREAD

**Issue by carlosmartel** [willowmagrini/ts_loterias#42]
@matheusgimenez 

A Api não está correta. Se está ACUMULOU então ninguem ganhou. 
O campo de busca está funcionando?
@andrenakazato @willowmagrini Design: campo de busca tem que estar no centro. 

![screen shot 2015-11-29 at 8 19 24 pm](https://cloud.githubusercontent.com/assets/5678578/11460552/8a402d64-96d5-11e5-88ae-c62c7ac03a15.png)

O último resultado é esse:

![screen shot 2015-11-29 at 8 20 20 pm](https://cloud.githubusercontent.com/assets/5678578/11460551/86e3da1c-96d5-11e5-889e-54e828dce0eb.png)

**Comment by andrenakazato** [comment]
@carlosmartel Por gentileza, veja sempre os resultados do homolog.sorteonline.com.br
![image](https://cloud.githubusercontent.com/assets/5948306/11460650/8f0c5e9c-96d7-11e5-891e-8b90fd82dbc6.png)
![image](https://cloud.githubusercontent.com/assets/5948306/11460652/a3794d22-96d7-11e5-9219-2735c02f7dd1.png)
A issue de resultado já está listada em https://github.com/willowmagrini/ts_loterias/issues/24
