### ISSUE TITLE
Exibiçao do Maiores Prêmios da Dupla incorreta

### ISSUE THREAD

**Issue by carlosmartel** [willowmagrini/ts_loterias#50]
Segunda data tá errada. 
![screen shot 2015-12-01 at 16 58 03](https://cloud.githubusercontent.com/assets/5678578/11510824/ba638cac-984c-11e5-9554-1e675a941608.png)

**Comment by andrenakazato** [comment]
https://github.com/willowmagrini/ts_loterias/blob/6abe3ee3a82e6677a1aeff75b359570bb7f7900e/page-dupla-sena.php

Aqui foi onde o design foi aplicado, precisa passar isso com API

**Comment by matheusgimenez** [comment]
feito no ultimo commit
