### ISSUE TITLE
Inserir API Estatisticas - Maiores Prêmios

### ISSUE THREAD

**Issue by carlosmartel** [willowmagrini/ts_loterias#52]
Não tem api. 
Tem api para premios individuais e acumulados?
A api traz quais foram os números sorteados? 
![screen shot 2015-12-01 at 17 26 59](https://cloud.githubusercontent.com/assets/5678578/11511541/d8d27708-9850-11e5-99cf-8dc7cb36c409.png)

**Comment by matheusgimenez** [comment]
feito no ultimo commit
