### ISSUE TITLE
Inserir API Estatisticas - Soma dos Números 

### ISSUE THREAD

**Issue by carlosmartel** [willowmagrini/ts_loterias#54]
http://eaxdesign.com.br/sorteonline/loterias-nacionais/dupla-sena/estatisticas/soma-dos-numeros/

Não tem API. No gráfico e na quantidade de vezes.

![screen shot 2015-12-01 at 17 47 57](https://cloud.githubusercontent.com/assets/5678578/11512122/c2159ccc-9853-11e5-91aa-52f9a4dcc772.png)

**Comment by matheusgimenez** [comment]
feito no ultimo commit
