### ISSUE TITLE
Inserir API Estatisticas - Linhas e Colunas

### ISSUE THREAD

**Issue by carlosmartel** [willowmagrini/ts_loterias#55]
Sem api.
Front: checar esse gráfico em outros browsers. Parece que o @andrenakazato  viu alguma coisa estranha no firefox. 

http://eaxdesign.com.br/sorteonline/loterias-nacionais/dupla-sena/estatisticas/linhas-e-colunas/

**Comment by willowmagrini** [comment]
@carlosmartel e @andrenakazato estou vendo a questão dos gráficos no firefox

**Comment by willowmagrini** [comment]
Já sei qual é o erro do gráfico, o uso da função calc no css, vou remover de todos os gráficos.

**Comment by carlosmartel** [comment]
Oba!
Em 01/12/2015 19:36, "willowmagrini" <notifications@github.com> escreveu:

**Comment by willowmagrini** [comment]
falta api

**Comment by matheusgimenez** [comment]
feito no ultimo commit
